import { GoogleGenAI } from "@google/genai";

/**
 * Interface for AI task generation
 */
export interface AIGenerationConfig {
  model?: "gemini-3.1-pro-preview" | "gemini-3-flash-preview";
  systemInstruction?: string;
  useSearch?: boolean;
}

/**
 * Centralized utility for Gemini AI interactions.
 * Handles API key verification and provides a clean interface for generation.
 */
export class AIService {
  private static instance: GoogleGenAI | null = null;

  private static getClient() {
    // Vite's define block replaces this at build time
    const apiKey = process.env.GEMINI_API_KEY;
    
    if (!apiKey || apiKey === "undefined") {
      throw new Error(
        "AI Configuration Error: GEMINI_API_KEY is missing. " +
        "If you are on Vercel or GitHub, please ensure the environment variable is added to your dashboard and you have redeployed the app."
      );
    }

    if (!this.instance) {
      this.instance = new GoogleGenAI({ apiKey });
    }
    return this.instance;
  }

  private static lastRequestTime = 0;
  private static MIN_REQUEST_INTERVAL = 1000; // 1 second between requests minimum

  /**
   * Generates content using the specified config
   */
  static async generateContent(prompt: string, config: AIGenerationConfig = {}) {
    const now = Date.now();
    const timeSinceLast = now - this.lastRequestTime;
    
    if (timeSinceLast < this.MIN_REQUEST_INTERVAL) {
      await new Promise(resolve => setTimeout(resolve, this.MIN_REQUEST_INTERVAL - timeSinceLast));
    }
    
    this.lastRequestTime = Date.now();
    
    const { 
      model = "gemini-3-flash-preview", 
      systemInstruction, 
      useSearch = false 
    } = config;

    try {
      const client = this.getClient();
      const aiModel = client.models.generateContent({
        model,
        contents: prompt,
        config: {
          ...(systemInstruction ? { systemInstruction } : {}),
        },
        ...(useSearch ? { tools: [{ googleSearch: {} }] } : {})
      });

      const response = await aiModel;
      return response.text || "No response generated by AI.";
    } catch (error: any) {
      console.error("AI Generation failed:", error);
      
      // Specialized error handling for common API issues
      if (error.message?.includes("API_KEY_INVALID")) {
        throw new Error("Invalid API Key. Please check your GEMINI_API_KEY setting.");
      }
      
      if (error.message?.includes("quota")) {
        throw new Error(
          "Rate Limit Exceeded: You've reached the 'Requests Per Minute' (RPM) limit for the Gemini API free tier. " +
          "Pro models allow ~2 requests per minute, while Flash allows ~15. " +
          "Please wait 60 seconds and try again."
        );
      }

      throw error;
    }
  }
}
