import { GoogleGenAI } from "@google/genai";

/**
 * Interface for AI task generation
 */
export interface AIGenerationConfig {
  model?: "gemini-3.1-pro-preview" | "gemini-3-flash-preview";
  systemInstruction?: string;
  useSearch?: boolean;
}

/**
 * Centralized utility for Gemini AI interactions.
 * Handles API key verification and provides a clean interface for generation.
 */
export class AIService {
  private static instance: GoogleGenAI | null = null;

  private static getClient() {
    // Vite's define block replaces this at build time
    const apiKey = process.env.GEMINI_API_KEY;
    
    if (!apiKey || apiKey === "undefined") {
      console.error("GEMINI_API_KEY is missing or undefined in current environment.");
      throw new Error(
        "AI Configuration Error: GEMINI_API_KEY is missing. " +
        "If you are on Vercel or GitHub, please ensure the environment variable is added to your dashboard and you have redeployed the app."
      );
    }

    console.log(`AI Service initialized with key: ${apiKey.substring(0, 4)}...${apiKey.substring(apiKey.length - 4)}`);

    if (!this.instance) {
      this.instance = new GoogleGenAI({ apiKey });
    }
    return this.instance;
  }

  private static readonly COOLOFF_KEY = "growthos_ai_cooloff_v2";
  private static readonly LAST_REQ_KEY = "growthos_ai_last_req_v2";
  private static readonly DAILY_QUOTA_KEY = "growthos_ai_daily_reset";

  private static getCooloffUntil(): number {
    const val = localStorage.getItem(this.COOLOFF_KEY);
    if (!val) return 0;
    const time = Number(val);
    // If the cooloff is more than 1 hour in the past, ignore it (stale data safety)
    if (Date.now() - time > 3600000) {
      this.resetSafetyPause();
      return 0;
    }
    return time;
  }

  private static setCooloffUntil(time: number) {
    localStorage.setItem(this.COOLOFF_KEY, time.toString());
  }

  private static getLastRequestTime(): number {
    return Number(localStorage.getItem(this.LAST_REQ_KEY) || "0");
  }

  static resetSafetyPause() {
    localStorage.removeItem(this.COOLOFF_KEY);
    localStorage.removeItem(this.LAST_REQ_KEY);
  }

  private static setLastRequestTime(time: number) {
    localStorage.setItem(this.LAST_REQ_KEY, time.toString());
  }
  
  private static executionQueue: Promise<any> = Promise.resolve();

  static async generateContent(prompt: string, config: AIGenerationConfig = {}) {
    // Check daily reset
    const today = new Date().toDateString();
    const lastReset = localStorage.getItem(this.DAILY_QUOTA_KEY);
    if (lastReset !== today) {
      localStorage.setItem(this.DAILY_QUOTA_KEY, today);
      // Optional: Clear other keys if it's a new day
      this.resetSafetyPause();
    }

    // Chain onto the current queue to ensure serial execution
    return this.executionQueue = this.executionQueue.then(async () => {
      const { 
        model = "gemini-3-flash-preview", 
        systemInstruction, 
        useSearch = false 
      } = config;

      const now = Date.now();
      const cooloff = this.getCooloffUntil();
      
      // Check for active cool-off
      if (now < cooloff) {
        const remaining = Math.ceil((cooloff - now) / 1000);
        throw new Error(`AI Limit Protect: Resuming in ${remaining}s. To save your free quota, I've paused AI across all your tabs temporarily.`);
      }

      // Pro has 2 RPM (30s avg), Flash has 15 RPM (4s avg)
      // We use slightly higher buffers to be safe
      const interval = model.includes("pro") ? 45000 : 6000; 
      const lastReq = this.getLastRequestTime();
      const timeSinceLast = now - lastReq;
      
      if (timeSinceLast < interval) {
        const waitTime = interval - timeSinceLast;
        await new Promise(resolve => setTimeout(resolve, waitTime));
      }
      
      this.setLastRequestTime(Date.now());

      try {
        const client = this.getClient();
        const aiModel = client.models.generateContent({
          model,
          contents: prompt,
          config: {
            ...(systemInstruction ? { systemInstruction } : {}),
          },
          ...(useSearch ? { tools: [{ googleSearch: {} }] } : {})
        });

        const response = await aiModel;
        return response.text || "No response generated by AI.";
      } catch (error: any) {
        console.error("AI Generation failed:", error);
        
        const errorMessage = error.message || "";
        
        if (errorMessage.includes("API_KEY_INVALID")) {
          throw new Error("Invalid API Key. Please check your GEMINI_API_KEY setting in Vercel.");
        }
        
        // Distinguish between RPM (Requests Per Minute) and RPD (Requests Per Day)
        if (errorMessage.includes("quota") || errorMessage.includes("429") || errorMessage.includes("limit")) {
          const now = Date.now();
          
          if (errorMessage.toLowerCase().includes("exhausted") || 
              errorMessage.toLowerCase().includes("limit reach") || 
              errorMessage.toLowerCase().includes("daily") || 
              errorMessage.toLowerCase().includes("quota")) {
             // Daily limit hits deserve a much longer pause (e.g. 1 hour) before retrying locally
             this.setCooloffUntil(now + 3600000); 
             throw new Error("Daily Limit Reached (1,500 reqs): You've hit the Gemini Free Tier daily cap. AI will reset tomorrow. Please check back then or use a different API key.");
          }

          // If we hit a standard 429 RPM error, trigger a 65-second safety pause across ALL TABS
          this.setCooloffUntil(now + 65000);
          throw new Error(
            "Rate Limit Exceeded: You're calling the AI too fast. I've activated a 65s 'Safety Pause' across all your tabs to protect your free quota. Please wait a minute before retrying."
          );
        }

        if (errorMessage.includes("503") || errorMessage.includes("overloaded")) {
          throw new Error("AI Server Busy: Google's AI servers are currently overloaded. Please try again in 30 seconds.");
        }

        throw new Error(`AI Error: ${errorMessage || "Connection failed. Please check your internet or API key."}`);
      }
    });
  }
}
